---
name: ci
on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    name: build resourcepack
    runs-on: ubuntu-20.04

    steps:
      - name: checkout this repo
        uses: actions/checkout@v2
        with:
          path: turtlelang

      - name: checkout minelittlepony repo
        uses: actions/checkout@v2
        with:
          repository: minelittlepony/minelittlepony
          path: minelittlepony

      - name: checkout hdskins repo
        uses: actions/checkout@v2
        with:
          repository: minelittlepony/hdskins
          path: hdskins

      - name: checkout presence footsteps repo
        uses: actions/checkout@v2
        with:
          repository: sollace/presence-footsteps
          path: presence-footsteps

      - name: Download Minecraft jar
        uses: autumnblazey/action-get-mc-jar@v1
        with:
          filename: minecraft.jar

      - name: get the json file out of jar
        run: |
          7z e -y -o minecraft -- minecraft.jar

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 15

        # yes this pack has a build process lol
        # automate the lowercasing of the things
        # because its error prone to do manually
      - name: build pack
        run: node turtlelang/scripts/build
